[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"]
working_directory = "/home/shreyas/work/"
# [colors.primary]
# background = "#000000"
# foreground = "#c5c8c6"
[window]
decorations_theme_variant = "Dark"
decorations           = "Full"
[font]
size = 11.0

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[[keyboard.bindings]]
chars = "tmux -u \u000D"
# command = { program = "tmux", args = ["-u"] }
key = "m"
mods = "Control"

[[keyboard.bindings]]
chars = "vi ~/.zshrc \u000D"
# command = { program = "tmux", args = ["-u"] }
key = "z"
mods = "Control"

[[keyboard.bindings]]
chars = "vi ~/.config/nvim/init.lua\u000D"
# command = { program = "tmux", args = ["-u"] }
key = "z"
mods = "Control|Shift"


[terminal.shell]
program = "/bin/zsh"

[scrolling]
history = 100000

[cursor.style]
shape = "Beam"
blinking="Always"

[cursor]
blink_timeout         = 3
